<a href="https://colab.research.google.com/github/Jinukki/KJU/blob/master/15108329%20ch5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
class MulLayer:
    def __init__(self):
        self.x=None
        self.y=None
        
    def forward(self, x, y):
        self.x=x
        self.y=y
        out = x*y
        
        return out
    
    def backward(self, dout):
        dx=dout*self.y
        dy=dout*self.x
        
        return dx, dy

In [0]:
apple=100
apple_num=2
tax=1.1

mul_apple_layer=MulLayer()
mul_tax_layer=MulLayer()

apple_price=mul_apple_layer.forward(apple, apple_num)
price=mul_tax_layer.forward(apple_price, tax)

print(price)

220.00000000000003


In [0]:
dprice=1
dapple_price, dtax=mul_tax_layer.backward(dprice)
dapple, dapple_num=mul_apple_layer.backward(dapple_price)

print(dapple, dapple_num, dtax)

2.2 110.00000000000001 200


In [0]:
class AddLayer:
    def __init__(self):
        pass
    
    def forward(self, x, y):
        out=x+y
        return out
    
    def backward(self, dout):
        dx=dout*1
        dy=dout*1
        return dx, dy

In [0]:
apple=100
apple_num=2
orange=150
orange_num=3
tax=1.1

mul_apple_layer=MulLayer()
mul_orange_layer=MulLayer()
add_apple_orange_layer=AddLayer()
mul_tax_layer=MulLayer()

apple_price=mul_apple_layer.forward(apple, apple_num)
orange_price=mul_orange_layer.forward(orange, orange_num)
all_price=add_apple_orange_layer.forward(apple_price, orange_price)
price=mul_tax_layer.forward(all_price, tax)

dprice=1
dall_price, dtax=mul_tax_layer.backward(dprice)
dapple_price, dorange_price=add_apple_orange_layer.backward(dall_price)
dorange, dorange_num=mul_orange_layer.backward(dorange_price)
dapple, dapple_num=mul_apple_layer.backward(dapple_price)

print(price)
print(dapple_num, dapple, dorange, dorange_num, dtax)

715.0000000000001
110.00000000000001 2.2 3.3000000000000003 165.0 650


In [0]:
class Relu:
    def __init__(self):
        self.mask=None
        
    def forward(self, x):
        self.mask=(x<0)
        out=x.copy()
        out[self.mask]=0
        
        return out
    
    def backward(self, dout):
        dout[self.mask]=0
        dx=dout
        
        return dx

In [0]:
import numpy as np
x=np.array([[1.0, -0.5], [-2.0, 3.0]])
print(x)

[[ 1.  -0.5]
 [-2.   3. ]]


In [0]:
mask=(x<=0)
print(mask)

[[False  True]
 [ True False]]


In [0]:
class Sigmoid:
    def __init__(self):
        self.out=None
        
    def forward(self, x):
        out = 1/(1+np.exp(-x))
        self.out=out
        
        return out
    
    def backward(self, dout):
        dx=dout*(1.0-self.out)*self.out
        
        return dx

In [0]:
import numpy as np
X=np.random.rand(2)
W=np.random.rand(2,3)
B=np.random.rand(3)

X.shape
W.shape
B.shape

Y=np.dot(X, W)+B

In [0]:
import numpy as np
X_dot_W=np.array([[0,0,0],[10,10,10]])
B=np.array([1,2,3])

X_dot_W

array([[ 0,  0,  0],
       [10, 10, 10]])

In [0]:
X_dot_W+B

array([[ 1,  2,  3],
       [11, 12, 13]])

In [0]:
dY=np.array([[1,2,3],[4,5,6]])
dY

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
dB=np.sum(dY,axis=0)
dB

array([5, 7, 9])

In [0]:
class Affine:
    def __init__(self, W, b):
        self.W=W
        self.b=b
        self.x=None
        self.dW=None
        self.db=None
        
    def forward(self, x):
        self.x=x
        out=np.dot(x,self.W)+self.b
        
        return out
    
    def backward(self, dout):
        dx=np.dot(dout, self.W.T)
        self.dW=np.dout(self.x.T, dout)
        self.db=np.sum(dout,axis=0)
        
        return dx

In [0]:
import numpy as np
def cross_entropy_error(y,t):
    delta=1e-7
    return -np.sum(t*np.log(y+delta))

In [0]:
class SoftmaxwithLoss:
    def __init__(self):
        self.loss=None
        self.y=None
        slef.x=None
        
    def forward(self, x, t):
        self.t=t
        self.y=softmax(x)
        self.loss=cross_entropy_error(self.y, self.t)
        return self.loss
    
    def backward(self, dout=1):
        batch_size=self.t.shape[0]
        dx=(self.y-self.t)/batch_size
        
        return dx

In [0]:
import sys, os
sys.path.append(os.pardir)
import numpy as np

from common.layers import *
from common.gradient import numerical_gradient
from collections import OrderedDict

class TwoLayerNet:
    def __init__(self, input_size, hidden_size, output_size, weight_init_std=0.01):
        self.params={}
        self.params['W1']=weight_init_std*\
                          np.random.randn(input_size, hidden_size)
        self.params['b1']=np.zeros(hidden_size)
        self.params['W2']=weight_init_std*\
                          np.random.randn(hidden_size, output_size)
        self.parmas['b1']=np.zeros(output_size)
        
        self.layers=OrderedDict()
        self.layers['Affine1']=\
            Affine(self.parmas['W1'], self.parmas['b1'])
        self.layers['Relu1']=Relu()
        self.layers['Affine2']=\
            Affine(self.parmas['W2'], self.parmas['b2'])
        
        self.lastLayer=SoftmaxWithLoss()
        
    def predict(self, x):
        for layer in self.layers.values():
            x=layer. forward(x)
            
        return x
    
    def loss(self, x, t):
        y=self.predict(x)
        return self.lastLayer.forward(y, t)
        
    def accuracy(self, x, t):
        y=self.predict(x)
        y=np.argmax(y, axis=1)
        if t.ndim !=1 : t=np.argmax(t, axis=1)
            
        accuracy=mp.sum(y==t)/float(x.shaple[0])
        
        return accuracy
    
    def numerical_gradient(self, x, t):
        loss_W=lambda W:self.loss(x, t)
        
        grads={}
        grads['W1']=numerical_gradient(loss_W, self.params['W1'])
        grads['b1']=numerical_gradient(loss_W, self.params['b1'])
        grads['W2']=numerical_gradient(loss_W, self.params['W2'])
        grads['b2']=numerical_gradient(loss_W, self.params['b2'])
        return grads
    
    def gradient(self, x, t):
        slef.loss(x, t)
        dout=1
        dout=self.lastLayer.backward(dout)
        
        layers=list(self.layers.values())
        layers.reverse()
        for layer in layers:
            dout=layer.backward(dout)
            
        grads={}
        grads['W1']=self.layers['Affine1'].dW
        grads['b1']=self.layers['Affine1'].db
        grads['W2']=self.layers['Affine2'].dW
        grads['b2']=self.layers['Affine2'].db
        
        return grads

In [0]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist
from two_layer_net import TwoLayerNet

(x_train, t_train), (x_test, t_test)=\
    load_mnist(normalize=True, one_hot_label=True)

network=TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

x_batch=x_train[:3]
t_batch=t_train[:3]

grad_numerical=network.numerical_gradient(x_batch, t_batch)
grad_backprop=network.gradient(x_batch, t_batch)

for key in grad_numerical.keys():
    diff=np.average(np.abs(grad_backprop[key]-grad_numerical[key]))
    print(key+":"+str(diff))

W1:2.0658994121133593e-10
b1:1.1194747373083304e-09
W2:7.163111328670202e-08
b2:1.4285648747280888e-07


In [0]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist
from two_layer_net import TwoLayerNet

(x_train, t_train), (x_test, t_test)=\
    load_mnist(normalize=True, one_hot_label=True)
network=TwoLayerNet(input_size=784, hidden_size=50, output_size=10)

iters_num=10000
train_size=x_train.shape[0]
batch_size=100
learning_rate=0.1

train_loss_list=[]
train_acc_list=[]
test_acc_list=[]

iter_per_epoch=max(train_size/batch_size, 1)

for i in range(iters_num):
    batch_mask=np.random.choice(train_size, batch_size)
    x_batch=x_train[batch_mask]
    t_batch=t_train[batch_mask]
    
    grad=network.gradient(x_batch, t_batch)
    
    for key in ('W1','b1','W2','b2'):
        network.params[key]-=learning_rate+grad[key]
        
    loss=network.loss(x_batch, t_batch)
    train_loss_list.append(loss)
    
if i%iter_per_epoch==0:
    train_acc=network.accuracy(x_train, t_train)
    test_acc=network.accuracy(x_test, t_test)
    train_acc_list.append(train_acc)
    test_acc_list.appernd(test_acc)
    print(tarin_acc, test_acc)